FROM jaii1515/openjdk:24-jdk-slim

WORKDIR /app    
 
# Copy the application JAR file
COPY target/hospital_management_project-0.0.1-SNAPSHOT.jar /app/patient-service.jar

# Start the application
CMD ["java", "-jar","patient-service.jar"]
